### ISSUE TITLE
Brunch build mention in readme

### ISSUE THREAD

**Issue by art4ride** [arjan/scribble#1]
The case is: If somebody new to phoenix tries to follow your Readme, they will fail because the static assets will be not yet compiled.
So it should be a good idea to mention `brunch build` command or include compiled assets in git(less preferred case)

**Comment by arjan** [comment]
Thanks, I'll fix this soon :)

**Comment by arjan** [comment]
Sorry for not responding :-) I upgraded to Phoenix 1.4 now and adjusted the instructions accordingly.
